### ISSUE TITLE
Your site is down

### ISSUE THREAD

**Issue by deb0rian** [Sylius/Sylius-Docs#278]
I want to demonstrate your platform to my management for future usage on big projects, and your website is down... for a week at least since I found this platform. Too bad. You're losing big name clients. :(

**Comment by aRn0D** [comment]
@deb0rian Can you install Sylius locally ?

**Comment by pjedrzejewski** [comment]
@deb0rian Dear Boris, sorry for the downtime, website and demo are much more stable right now. Thanks for raising this issue! :+1:
