### ISSUE TITLE
Api Error 403 Acces denied

### ISSUE THREAD

**Issue by tuxado** [Sylius/Sylius-Docs#289]
i use a local server 192.168.1.168 and i generate secret and client id from git bash and i generate a token and when i try to get the users list o add product from the api i get {"code":403,"message":"Access Denied"}

$ curl --include --request GET 'http://192.168.1.168/app_dev.php/api/users/' --
header 'Authorization: Bearer ZjRjNjFlZjQ0ZWIxODY1OTc1ZDUzYTFkNGE0ZTY5OGZmM2U4Z
WI2ODIzNTIyNWU0NzAyNjMzM2Y2MzI5OTBhYQ'
HTTP/1.1 403 Forbidden
Date: Sun, 07 Jun 2015 01:24:55 GMT
Server: Apache/2.4.7 (Win32) PHP/5.4.24
X-Powered-By: PHP/5.4.24
Set-Cookie: PHPSESSID=k5jr84alke288fnjh2ig878s61; path=/
Cache-Control: no-cache
X-Debug-Token: 10da68
X-Debug-Token-Link: /app_dev.php/_profiler/10da68
Content-Length: 38
Content-Type: application/json

{"code":403,"message":"Access Denied"}

any idea how fix it?
perhubs i made error in the commande line?

**Comment by pjedrzejewski** [comment]
Should be fixed in #2818.
