### ISSUE TITLE
build documentation

### ISSUE THREAD

**Issue by gseidel** [Sylius/Sylius-Docs#294]
Hello, im trying to contribute to this documentation. So my first step was to build it. The readme says, just execute

```shell
$ bin/build
```
but this file doesn't exists. Maybe it was removed before? If yes, then why?

I instead use the ```sphinx-build``` command.

```shell
$ sphinx-build -b html . build
```

So the readme should be updated or the ```bin/build``` should be created.

**Comment by pjedrzejewski** [comment]
Fixed in https://github.com/Sylius/Sylius-Docs/commit/17a00b201d321983c18e5de4701b2703bd319ef9, thanks for reporting Gerhard! :+1:
