### ISSUE TITLE
Can`t use math extension

### ISSUE THREAD

**Issue by YVAlNE** [Sylius/Sylius-Docs#432]
Hello, 

I need to use mathamatics in my documentation, therefore i want to use the extension sphinx.ext.imgmath. With sphinx version 1.4.1 it does not work. Same error 
[https://github.com/Sylius/Sylius-Docs/issues/420](url)

then  i decided to downgrade my sphinx version now im using 1.3.6 and sphinx.ext.png
`extensions = ['sphinx.ext.autodoc','sphinx.ext.pngmath','rst2pdf.pdfbuilder']`

now i can build my project without any errors or warnings, however it still dont work -.-
i try to put in this in my rst-file 

`.. math::

   1/u + 1/v = 1/F_a`

Is there any other syntax for math in sphinx version 1.3.6 ? 

thanks for your help

**Comment by pjedrzejewski** [comment]
Hi @YVAlNE, could you open this issue on our main repo? This one is depracated. Thank you!

**Comment by YVAlNE** [comment]
Sorry

**Comment by pjedrzejewski** [comment]
@YVAlNE No worries! :)
