### ISSUE TITLE
Sylius : Could not load type “app.form.type.slider”

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius-Docs#433]
the form type service can't be defined !!!

AppBundle/Resources/config/routing.yml:

`app_slider_create:
path: /sliders/slider/new
methods: [GET, POST]
defaults:
    _controller: app.controller.slider:createAction
    _sylius:
        form: app.form.type.slider`

AppBundle/Resources/config/services.yml:
`app.form.type.slider:
    class: AppBundle\Form\Type\add_img_sliderType
    tags:
                - { name: form.type, alias: app_slider }
    arguments: [@doctrine, @sylius.context.locale]`

**Comment by pjedrzejewski** [comment]
Slide has been removed in dev-master branch, so it is no longer used. Sorry!

**Comment by yosriMekni** [comment]
okey  ,but  is there an other way to display a slider ?
