### ISSUE TITLE
Sylius : add entity administrator to admin panel

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius-Docs#434]
*excuse my english . I have created a new entity  and i want to add it's adminisrator to admin panel in admin dashboard i've followed the steps in the sylius docs but no changes :
AppBundle/Resources/config.services.yml:

`services:
app.admin.menu_builder_listener:
    class: AppBundle\EventListener\MenuBuilderListener
    tags:
        - { name: kernel.event_listener, event: sylius.menu_builder.backend.main, method: addBackendMenuItems }
        - { name: kernel.event_listener, event: sylius.menu_builder.backend.sidebar, method: addBackendMenuItems }`
AppBundle\EventListener\MenuBuilderListener.php :

`<?php

namespace AppBundle\EventListener;

use Sylius\Bundle\UiBundle\Menu\Event\MenuBuilderEvent;
use Sylius\Bundle\WebBundle\Event\MenuBuilderEvent as FrontendMenuBuilderEvent;

class MenuBuilderListener
{
    /**
     \* @param MenuBuilderEvent $event
 */
public function addBackendMenuItems(MenuBuilderEvent $event)
{
    $menu = $event->getMenu();

```
$menu->addChild('backend_main')
    ->setLabel('Test Backend Main');
```

}

/**
- @param FrontendMenuBuilderEvent $event
  */
  public function addFrontendMenuItems(FrontendMenuBuilderEvent $event)
  {
  $menu = $event->getMenu();
  
  $menu->addChild('frontend')
      ->setLabel('Frontend Menu Item');
  }
  }`
  its actually not loading the config.services.yml ! why ?! what can be the problem ! plz help

**Comment by CoderMaggie** [comment]
Hi! Why did you open this issue here? It's an abandoned repo.

Are you following these docs -> http://docs.sylius.org/en/latest/customization/menu.html ?

**Comment by yosriMekni** [comment]
hi , oh i didnt noticed that sorry.
yes i followed that docs but no chance :/

**Comment by CoderMaggie** [comment]
yeah. I see a mistake here. 

Rename `AppBundle\Resources\config.services.yml` -> `AppBundle\Resources\config\services.yml`

**Comment by yosriMekni** [comment]
no changes in the admin panel , so strange :/

**Comment by CoderMaggie** [comment]
have you cleared your cache?

**Comment by yosriMekni** [comment]
yes i cleared it , where i suppose to see the changes exactly ? maybe i'm seeing in some where else, excuse my english
